# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Site settings
title: Ben's Blofg
author: Tomáš Beňo
email: benjiko99@gmail.com
description: >- # this means to ignore newlines until the next tag
  Resources related to Android, Android Studio and Git.
google_analytics: UA-37672995-6

# Social sites
twitter_username: benjiko99
github_username: benjiko99
linkedin_username: benjiko99

# Collections
collections:
  refactoring:
    output: true
  architecture:
    output: true
  git:
    output: true
  android:
    output: true
  android_studio:
    output: true
  clean_code:
    output: true
  references:
    output: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
